# Generated by Django 3.1.4 on 2022-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_salao', models.CharField(max_length=6)),
                ('id_usuario_cliente', models.CharField(max_length=6)),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('data', models.DateField()),
                ('valor_total', models.FloatField()),
                ('duracao_total', models.TimeField()),
            ],
        ),
    ]
