# Generated by Django 3.1.4 on 2022-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='id_usuario_cliente',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='cliente',
            field=models.CharField(default='', max_length=200),
        ),
    ]
