# Generated by Django 3.1.4 on 2022-12-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_auto_20221201_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='id_procedimento',
            field=models.CharField(default='', max_length=6),
        ),
    ]
