# Generated by Django 3.1.4 on 2022-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao', models.TimeField()),
                ('valor', models.FloatField()),
                ('id_usuario', models.CharField(max_length=6)),
            ],
        ),
    ]
