# Generated by Django 3.1.4 on 2022-12-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentos',
            name='id_procedimento',
            field=models.CharField(default='', max_length=6),
        ),
    ]
