# Generated by Django 3.1.4 on 2022-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_auth_user',
            field=models.CharField(default='', max_length=8),
        ),
    ]
