# Generated by Django 3.1.4 on 2022-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_usuario_codigo_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='salao',
            field=models.BooleanField(default='False'),
        ),
    ]
