# Generated by Django 3.1.4 on 2022-12-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20221110_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='salao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url',
        ),
    ]
